language: r
cache: packages
warnings_are_errors: false
sudo: false

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   env:
    #     - R_CODECOV=true
    #     - MAKEFLAGS="-j 2"
    - os: osx
      latex: false

r_github_packages:
  - richfitz/RcppR6
  - richfitz/grader
  - smbache/loggr
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:DPfom03G2FgVC9z69XMi9g4L
