language: r
cache:
  packages: true
  apt: true
warnings_are_errors: false

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

branches:
  except:
    - gh-pages
    - remove_plant_plus
    - scaffolder

r_binary_packages: 
  - devtools
  - roxygen2

r_github_packages:
  - richfitz/RcppR6
  - richfitz/grader
  - smbache/loggr
  - jimhester/covr
      
jobs:
  include:
    - os: linux
      dist: bionic
      env:
        - R_CODECOV=true
        - MAKEFLAGS="-j 2"
    - os: osx
      latex: false

script: | 
  R CMD build .
  R CMD check plant*tar.gz --no-tests --no-manual 
  Rscript -e 'devtools::install();devtools::test()'
  pass=$?
  if [[ $pass -ne 0 || $(grep -i "WARNING\|ERROR" plant.Rcheck/00check.log) != "" ]]; then
    (exit 1)
  else
    (exit 0)
  fi

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack: traitecoevo:pYviKwrn6lAvBZUOxxktBwcO
